// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';
import {types} from '../models';
import {models} from '../models';

export function AnilistLogin(arg1:string):Promise<backend.LoginStatus>;

export function AnilistStatus():Promise<backend.AnilistStatus>;

export function DomReady(arg1:context.Context):Promise<void>;

export function MangaIndex():Promise<Array<types.ALMediaListGroup>>;

export function SignIn(arg1:string,arg2:string):Promise<models.Account>;

export function SignOut():Promise<void>;
