// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {models} from '../models';

export function DomReady(arg1:context.Context):Promise<void>;

export function SignIn(arg1:string,arg2:string):Promise<models.Account>;
