// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnilistLogin(arg1) {
  return window['go']['backend']['App']['AnilistLogin'](arg1);
}

export function AnilistStatus() {
  return window['go']['backend']['App']['AnilistStatus']();
}

export function DomReady(arg1) {
  return window['go']['backend']['App']['DomReady'](arg1);
}

export function MangaIndex() {
  return window['go']['backend']['App']['MangaIndex']();
}

export function MangaShow(arg1) {
  return window['go']['backend']['App']['MangaShow'](arg1);
}

export function SignIn(arg1, arg2) {
  return window['go']['backend']['App']['SignIn'](arg1, arg2);
}

export function SignOut() {
  return window['go']['backend']['App']['SignOut']();
}
