# name: Run Ginkgo Tests

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: 1.23.0

#       - name: Install dependencies
#         run: go mod tidy

#       - name: Install Ginkgo
#         run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

#       - name: Run Ginkgo tests
#         run: ginkgo -r
